/*
 * Copyright (c) 2019 Thermo Fisher Scientific
 * All rights reserved.
 */


/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * <p>
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * <p>
 * Let us list the factors of the first seven triangle numbers:
 * <p>
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * <p>
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class HighlyDivisibleTriangularNumber
{
    /**
     * TODO: Field description
     */
    static final int FACTORS_MAX = 500;

    /**
     * Main
     *
     * @param args
     */
    public static void main(String[] args)
    {
        long triangleNumber = 0;
        int factorsCount = 0;
        int i = 1;

        while (factorsCount <= FACTORS_MAX)
        {
            factorsCount = 0;
            triangleNumber = triangleNumber + i++;

            System.out.println("\nTriangle Number " + triangleNumber);

            for (int j = 1; j <= Math.sqrt(triangleNumber); j++)
            {
                if (triangleNumber % j == 0)
                {
                    factorsCount++;
                }
            }

            factorsCount *= 2;
            System.out.print(" factor count = " + factorsCount);
        }
    }
}

