/*
 * Copyright (c) 2019 Thermo Fisher Scientific
 * All rights reserved.
 */


/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class PrintNodeOfKDistance
{
    /**
     * Main
     *
     * @param args
     */
    public static void main(String[] args)
    {
        BinaryTree tree = new BinaryTree();

        tree.root = new Node(1);
        tree.root.left = new Node(2);
        tree.root.right = new Node(3);
        tree.root.left.left = new Node(4);
        tree.root.left.right = new Node(5);
        tree.root.right.left = new Node(8);

        tree.printKDistant(tree.root, 1);
    }

    static class Node
    {
        int data;
        Node left, right;

        Node(int item)
        {
            data = item;
            left = right = null;
        }
    }

    static class BinaryTree
    {
        Node root;

        void printKDistant(Node node, int k)
        {
            if (node == null)
            {
                return;
            }
            if (k == 0)
            {
                System.out.print(node.data + " ");
                return;
            }
            else
            {
                printKDistant(node.left, k - 1);
                printKDistant(node.right, k - 1);
            }
        }
    }
}

